openapi: 3.0.2
info:
  version: 1.0.0
  title: Workstream Public Applicants Imported Employee Infos API
  termsOfService: https://workstream.us/terms/
  contact:
    email: help@workstream.is
    url: https://help.workstream.us/en/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: workstream-logo.svg
    href: '#'
  description: '# API Reference


    The Workstream API is a modern, [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer) API. Our API has predictable resource-oriented URLs, supports HTTPS authentication, verbs and response codes, and returns JSON-encoded responses.


    **Note:** [Old APIs](https://old-api-doc.workstream.us/) will be deprecated, please refer to this API documentation for new API usages.

    '
servers:
- url: https://{tenant}
  variables:
    tenant:
      default: public-api.workstream.us
      description: Public API URI
tags:
- name: Imported Employee Infos
  description: Imported Employee Infos represent imported employee information that is associated with employees within your company.
paths:
  /imported_employee_infos:
    get:
      operationId: ListImportedEmployeeInfos
      tags:
      - Imported Employee Infos
      summary: List existing Imported Employee Infos
      description: List existing Imported Employee Infos
      security:
      - bearerAuth: []
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          example: 1
        description: The page number to retrieve.
      - name: per_page
        in: query
        schema:
          type: integer
          example: 10
        description: The number of items to retrieve per page, maximum is 100.
      responses:
        '200':
          description: Returns the imported employee info list.
          headers:
            X-Request-ID:
              schema:
                type: string
              description: A randomly generated request_id to uniquely identify each request sent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imported_employee_infos:
                    type: array
                    items:
                      $ref: '#/components/schemas/show'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '422':
          $ref: '#/components/responses/422'
        '429':
          $ref: '#/components/responses/429'
components:
  schemas:
    show:
      type: object
      title: Imported Employee Info
      properties:
        first_name:
          type: string
          description: Imported employee's first name.
          example: Tom
        last_name:
          type: string
          description: Imported employee's last name
        phone:
          type: string
          description: Imported employee's phone number
          example: '+17789882873'
        email:
          type: string
          description: Imported employee's email address
        rehire_eligiblity:
          type: string
          description: Imported employee's rehire eligibility
          enum:
          - eligible
          - not_eligible
          nullable: true
        termination_reason:
          type: string
          description: Imported employee's termination reason
  responses:
    '422':
      description: Unprocessable Entity - Invalid query params or request body.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 13422
              message:
                type: string
                example: (forbidden_embedded_resources}) is not a supported 'embed'. Valid 'embed' keys are (permitted_embedded_resources).
    '403':
      description: Forbidden - The user is not authorized to use this resource.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 13403
              message:
                type: string
                example: Forbidden - The user is not authorized to use this resource.
    '401':
      description: Unauthorized - Credentials are not valid for the target resource.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 13401
              message:
                type: string
                example: Unauthorized
    '429':
      description: Too many requests.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              error_code:
                type: integer
                example: 13429
              message:
                type: string
                example: Throttle limit reached. Limit to 100 requests in 60 seconds.
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://public-api.workstream.us/
          scopes:
            Applicants: Read Applicant records
            Employees: Read Employee records
            Company Users: Read Company User records
            Company Roles: Read Company Role records
            Positions: Read Position records
            TeamMember: Read Team Member records
            Locations: Read Location records
            Departments: Read Department records
            Imported Employee Infos: Read Imported Employee Info records
            Custom Field: Read, update custom field and custom field values
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
